name: Test

on:
  push:
    branches:
      - main
      - work
  pull_request:
    branches:
      - main

jobs:
  test-demos:
    name: Test demos using ${{ matrix.bundler }} on node ${{ matrix.node }} with ${{ matrix.strategy }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - "14"
          - "16"
          - "18"
        bundler:
          - vite
          - webpack
        strategy:
          - isolated
          - hoisted
          - pnp

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Add pnpm config
        run: |-
          cat>.npmrc<<EOF
          engine-strict=true
          node-version=14.18.0
          node-linker=${{ matrix.strategy }}
          ${{ matrix.strategy == 'pnp' && 'symlink=false' || '' }}
          EOF

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      # test with specific node version
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: ${{ matrix.bundler }} build test
        run: |
          pnpm run -r demo:${{ matrix.bundler }}-build

  linter-and-unit:
    name: Linter and Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add pnpm config
        run: |-
          cat>.npmrc<<EOF
          engine-strict=true
          node-version=14.18.0
          EOF

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Linter test
        run: |
          pnpm run lint:check
          pnpm run lint:md

      - name: Unit test
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run test

      - name: Upload coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
